
   name: Deploy to GitHub Pages

   on:
     push:
       branches:
         - master # Adjust to the branch you want to trigger deployment from

   jobs:
     deploy:
       runs-on: ubuntu-latest
       continue-on-error: true
       steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
            java-version: '11'
            distribution: 'temurin'
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
         with:
            gradle-version: 7.4.2     ### This version will be installed and added to PATH, so used for cache-cleanup
       - name: Make gradlew executable
         run: chmod +x ./gradlew
       - name: Execute build with Gradle wrapper
         run: ./gradlew build clean test      
       - name: Dqwq
         if: always()
         uses: peaceiris/actions-gh-pages@v3
         with:
           publish_dir: ./build/GradleReports # Adjust to the directory containing your built site
           github_token: ${{ secrets.GITHUB_TOKEN }}
     nwtask:  
         needs: deploy
         if: needs.deploy.result == 'success' 
         runs-on: ubuntu-latest
         steps:
          - name: Install pythib
            uses: actions/setup-python@v3
          - name: Install pandoc
            run: |
               sudo apt-get install -y pandoc
          - name: Install pandora
            run: |
               pandoc -f html -t markdown_strict -o test-report.md index.html
               echo ":: set-output name=report::$(cat $1)" 
          - name: disp html summ in report page
            run: |
               chmod +x display-report.sh
               ./display-report.sh
               test-report.md
            id: display_report
