name: Publish HTML Report

on:
  workflow_run:
    workflows: ["Java CI with Gradle"] # Replace with your main workflow name
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Download the artifact
      - name: Download HTML Report Artifact
        uses: actions/download-artifact@v2
        with:
          name: test-report # Replace with the name of your artifact

      # Configure Git and GitHub Pages
      - name: Set up Git and Configure User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "komeershettyvinod@gmail.com"
          echo ".github/workflows" >> .gitignore

      # Create a new branch to publish the HTML report
      - name: Create Report Branch
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Publish HTML report"
          git push -u origin gh-pages

      # Publish the HTML report to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/GradleReports/index.html # Change to the directory containing your HTML report
